### ISSUE TITLE
[QUESTION] ACEX & ALiVE compat

### ISSUE THREAD

**Issue by Pyth3rEx** [tebsu/pdb#1]
Hey, I'm looking into adding your mod but we are using the ALiVE persistence for now. Has this mod been tested with it and how does it perform? (does it save the ALiVE AI commander?).

Also we'd like to save our ACEX food & water levels, is that taken into account when saving via this mod?

Thank you.

**Comment by schbaeggle** [comment]
It plainly saves objects, vehicles and players (each with position, loadout, state). It does not save any other, mainly third-party, states like food/water levels or commaner states. We currently did not test PDB in combination with ALIVE, can't tell anything about that.

**Comment by tebsu** [comment]
As we do not plan to play with ALiVE, there will be no development towards it. We could rewrite it a bit for the food and water levels, but i have no idea what the ALiVE AI commander is or what he does
